/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelos.Directorio;
import Modelos.UpdateTableListener;

/**
 *
 * @author Luismi
 */
public class ModificarHoras extends javax.swing.JDialog {
    private Directorio directorio;
    private UpdateTableListener listener;
    /**
     * Creates new form ModificarHoras
     */
    public ModificarHoras(java.awt.Frame parent, boolean modal, Directorio dir, UpdateTableListener listener) {
        super(parent, modal);
        initComponents();
        pack();
        this.directorio = dir;
        this.listener = listener;
        // Establecemos los valores actuales
        int horas = (int) (dir.getModificador() / 1000 / 60 / 60);
        
        spinnerHour.setValue(horas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spinnerHour = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar horas");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("Diferencia de");
        getContentPane().add(jLabel1);

        spinnerHour.setModel(new javax.swing.SpinnerNumberModel(0, -23, 23, 1));
        getContentPane().add(spinnerHour);

        jLabel2.setText("horas");
        getContentPane().add(jLabel2);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int horas = (int) spinnerHour.getValue();
        
        this.directorio.modificarTiempo(horas);
        this.listener.actualizarTabla();
        
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spinnerHour;
    // End of variables declaration//GEN-END:variables
}
