/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Mezclador;
import Modelos.Archivo;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Luismi
 */
public class Principal extends javax.swing.JFrame {
    private ArrayList<Archivo> archivos;
    private DefaultListModel<String> listaDirectorios;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initExtras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGoWork = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        pbProgress = new javax.swing.JProgressBar();
        labelCurrentFile = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAddDirectory = new javax.swing.JButton();
        btnRemoveDirectory = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfOutputPath = new javax.swing.JTextField();
        btnSelectDirectory = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDirectories = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Picture Mixer");
        setName("Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnGoWork.setText("Mezclar");
        btnGoWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoWorkActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoWork, java.awt.BorderLayout.LINE_END);

        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        pbProgress.setName(""); // NOI18N
        jPanel6.add(pbProgress, java.awt.BorderLayout.LINE_START);
        jPanel6.add(labelCurrentFile, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 5));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        btnAddDirectory.setText("Añadir carpeta");
        btnAddDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDirectoryActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddDirectory);

        btnRemoveDirectory.setText("Eliminar seleccionadas");
        btnRemoveDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDirectoryActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemoveDirectory);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Carpeta de salida:");
        jPanel4.add(jLabel1);
        jPanel4.add(tfOutputPath);

        btnSelectDirectory.setText("Seleccionar carpeta");
        btnSelectDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectDirectoryActionPerformed(evt);
            }
        });
        jPanel4.add(btnSelectDirectory);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(listDirectories);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectDirectoryActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setDialogTitle("Selecciona la carpeta de salida");
        fc.setApproveButtonText("Seleccionar");
        if(fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            tfOutputPath.setText(fc.getSelectedFile().toString());
        }        
    }//GEN-LAST:event_btnSelectDirectoryActionPerformed

    private void btnAddDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDirectoryActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setDialogTitle("Selecciona la carpeta para añadir");
        fc.setApproveButtonText("Seleccionar");
        if(fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            listaDirectorios.addElement(fc.getSelectedFile().toString());
        }     
    }//GEN-LAST:event_btnAddDirectoryActionPerformed

    private void btnRemoveDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDirectoryActionPerformed
        int selected[] = listDirectories.getSelectedIndices();
        for(int i = selected.length-1; i >= 0; i--) {
            listaDirectorios.removeElementAt(i);
        }
    }//GEN-LAST:event_btnRemoveDirectoryActionPerformed

    private void btnGoWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoWorkActionPerformed
        // De momento sin hilos, en la siguiente versión lo paso a segundo plano.
        activarControles(false);
        Mezclador mez = new Mezclador();
        for(int i=0; i<listaDirectorios.size(); i++) {
            mez.addDirectorio(listaDirectorios.get(i));
        }
        mez.mezclar(tfOutputPath.getText());
        activarControles(true);
    }//GEN-LAST:event_btnGoWorkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal p = new Principal();
                p.setLocationRelativeTo(null);  // Centrado en la pantalla
                p.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDirectory;
    private javax.swing.JButton btnGoWork;
    private javax.swing.JButton btnRemoveDirectory;
    private javax.swing.JButton btnSelectDirectory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurrentFile;
    private javax.swing.JList<String> listDirectories;
    private javax.swing.JProgressBar pbProgress;
    private javax.swing.JTextField tfOutputPath;
    // End of variables declaration//GEN-END:variables

    private void initExtras() {
        archivos = new ArrayList<Archivo>();
        listaDirectorios = new DefaultListModel<String>();
        
        listDirectories.setModel(listaDirectorios);
    }
    
    private void activarControles(boolean activar) {
        listDirectories.setEnabled(activar);
        btnAddDirectory.setEnabled(activar);
        btnRemoveDirectory.setEnabled(activar);
        tfOutputPath.setEnabled(activar);
        btnSelectDirectory.setEnabled(activar);
    }
}
